{% set name = "transaction" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65d0b1ea92dbe7c4e3b237fb6bd8b41dea23d7459e7bdd8c3880bffdaf912fa4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - setuptools
    - zope.interface

test:
  imports:
    - transaction
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/transaction
  license_file: LICENSE.txt
  license: ZPL-2.1
  license_family: OTHER
  summary: Transaction management for Python

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
