{% set name = "transaction" %}
{% set version = "3.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "3b0ad400cb7fa25f95d1516756c4c4557bb78890510f69393ad0bd15869eaa2d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - zope.interface

test:
  imports:
    - transaction

about:
  home: https://github.com/zopefoundation/transaction
  license_file: LICENSE.txt
  license: ZPL 2.1
  license_family: OTHER
  summary: 'Transaction management for Python'

extra:
  recipe-maintainers:
    - pmlandwehr
